### ISSUE TITLE
ability to activate libjxl/nonfree.

### ISSUE THREAD

**Issue by zedd-0** [AnimMouse/ffmpeg-autobuild#1071] opened 2024-06-12 18:04 UTC
hello, is it possible to enable libjxl, or does it violate the nonfree policy?
Is nonfree important to you, or would you consider switching to nonfree?

**Comment by AnimMouse** [comment] 2024-06-13 12:22
> hello, is it possible to enable libjxl

Yes it is possible, I'm just waiting for the upstream to add libjxl. Duplicate of #956.

> does it violate the nonfree policy?

Of course not.

> Is nonfree important to you

Yes, very important.

> would you consider switching to nonfree?

This is already nonfree.

**Closed** 2024-06-13 12:33 UTC
Labels: question
