### ISSUE TITLE
Bitrate counter and time counter are not working properly, since various versions

### ISSUE THREAD

**Issue by aventyne** [AnimMouse/ffmpeg-autobuild#1070] opened 2024-04-21 07:51 UTC
Hello there.
I'm using ffmpeg with non free codecs like libfdk aac, and versions are not working properly with time and bitrate counters.

Also, x265 is working slower than any other versiones like  BtbN, half speed aprox, I don't know why.

Sorry about my english.
Thank you and regards.

**Comment by AnimMouse** [comment] 2024-04-22 14:50
> Also, x265 is working slower than any other versiones like BtbN, half speed aprox, I don't know why.

https://github.com/AnimMouse/ffmpeg-stable-autobuild/issues/131

**Comment by AnimMouse** [comment] 2024-04-22 14:51
> versions are not working properly with time and bitrate counters.

Kindly paste here the output of your FFmpeg while encoding.

**Comment by aventyne** [comment] 2024-04-22 18:19
![Captura de pantalla 2024-04-22 201723](https://github.com/AnimMouse/ffmpeg-autobuild/assets/167674012/fd8b5bcb-4a40-48ab-8483-fb3ca6735d49)

![Captura de pantalla 2024-04-22 201737](https://github.com/AnimMouse/ffmpeg-autobuild/assets/167674012/48cc71ce-4ab8-4f8d-b576-09451bde0d21)


Only a few example of this. Check fps are higher but time it's not.

At the begging it's a good example, time is ???? and bitrate also.

It's possible to fix x265?

**Comment by AnimMouse** [comment] 2024-04-24 15:19
> Only a few example of this. Check fps are higher but time it's not.

I can't reproduce that bug, on my side, the time and frames are correct, can you specify what exact FFmpeg commit did you use?
It is also possible that the video you are converting on FFmpeg has broken timestamps. Are all the videos you tried also has wrong time and frame counters?

> It's possible to fix x265?

Yes, we will wait upstream to fix that `[noasm]` bug on libx265.

**Comment by AnimMouse** [comment] 2024-05-05 06:12
@aventyne Can you try this [specific FFmpeg release](https://github.com/AnimMouse/ffmpeg-autobuild/releases/tag/2024-05-04-15-15-df868ba-d5fe5f4) to check if the problem has been fixed?

**Comment by aventyne** [comment] 2024-05-05 08:07
Seems fixed. 
Optimizations are on.
But some other compilations still a bit faster.
Anyway, I normally use HE-AAC, can you confirm that is quite slow to code than OPUS?
Will be soon a new stable version?
Thank you anyway.

**Comment by AnimMouse** [comment] 2024-05-06 06:33
> Seems fixed.
Optimizations are on.

Nice to hear that

> But some other compilations still a bit faster.

Yea, our builds are somewhat "bloated" to accommodate all features not found on the official builds.

> Anyway, I normally use HE-AAC, can you confirm that is quite slow to code than OPUS?

```powershell
Measure-Command {Start-Process ffmpeg -argumentlist "-i test.flac -vn -c:a libopus -b:a 64k test.opus" -Wait}

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 2
Milliseconds      : 33
Ticks             : 20332104
TotalDays         : 2.35325277777778E-05
TotalHours        : 0.000564780666666667
TotalMinutes      : 0.03388684
TotalSeconds      : 2.0332104
TotalMilliseconds : 2033.2104
```
```powershell
Measure-Command {Start-Process ffmpeg -argumentlist "-i test.flac -vn -c:a libfdk_aac -profile:a aac_he -b:a 64k test_v1.m4a" -Wait}

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 3
Milliseconds      : 33
Ticks             : 30330099
TotalDays         : 3.510428125E-05
TotalHours        : 0.00084250275
TotalMinutes      : 0.050550165
TotalSeconds      : 3.0330099
TotalMilliseconds : 3033.0099
```
```powershell
Measure-Command {Start-Process ffmpeg -argumentlist "-i test.flac -vn -c:a libfdk_aac -profile:a aac_he_v2 -b:a 64k test_v2.m4a" -Wait}

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 2
Milliseconds      : 32
Ticks             : 20322320
TotalDays         : 2.35212037037037E-05
TotalHours        : 0.000564508888888889
TotalMinutes      : 0.0338705333333333
TotalSeconds      : 2.032232
TotalMilliseconds : 2032.232
```
Yes, HE-AAC is slower than Opus, but HE-AAC v2 is almost as fast as Opus.

> Will be soon a new stable version?

Yes, as soon as https://github.com/rdp/ffmpeg-windows-build-helpers/pull/738 got merged in the upstream. For the meantime, you can download an artifact [here](https://github.com/AnimMouse/ffmpeg-stable-autobuild/actions/runs/8955624843) for stable version.

> Thank you anyway.

You're welcome

**Closed** 2024-05-17 12:23 UTC
Labels: upstream bug
